# -*- coding: utf-8 -*-
{
    'name': 'marvelfields',
    'version': '18.0.0.0',
    'license': 'LGPL-3',
    'author': 'Setu Consulting Services Pvt. Ltd.',
    'website': 'https://www.setuconsulting.com',
    'support': 'support@setuconsulting.com',
    'depends': ['delivery', 'product', 'account', 'website_sale_stock', 'hr', 'contacts', 'base_vat',
                'approvals', 'crm', 'purchase', 'account_followup', 'mail', 'sale_order_multi_warehouse'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/partner_zone.xml',
        'data/send_product_information_data_cron.xml',
        'data/email_templates.xml',
        'data/payment_days.xml',
        'wizard/account_move_reversal_view.xml',
        'views/res_partner.xml',
        'views/compatible.xml',
        'views/product_template.xml',
        'views/payment_days.xml',
        'views/product_product.xml',
        'views/res_partner_zone.xml',
        'views/templates.xml',
        'views/origin_database.xml',
        'views/temporary.xml',
        'views/sale_order.xml',
        'views/stock_warehouse.xml',
        'views/delivery_carrier.xml',
        'views/approval_category.xml',
        'views/approval_request.xml',
        'views/hr_employee_base.xml',
        'views/purchase_order.xml',
        'views/stock_picking.xml',
        'views/shipping_incident.xml',
        'views/stock_location.xml',
        'views/clasificaciones.xml',
        'views/res_config_setting.xml',
        'views/subclases.xml',
        'views/product_supplierinfo.xml',
        'views/stock_quant_view.xml',
    ],
    'application': True,
    'assets': {
        'web.assets_frontend': [
            'marvelfields/static/src/website_sale_payment.js',
        ]
    }
}
