{
    "name": "Stock Cycle Count",
    "summary": "Adds the capability to schedule cycle counts in a "
               "warehouse through different rules defined by the user.",
    "version": "18.0.0.0",
    "author": "Setu Consulting",
    "website": "https://www.setuconsulting.com",
    "category": "Warehouse Management",
    "depends": ["stock_account",'stock_barcode'],
    "data": [
        # 'data/ir.model.fields.csv',
        'security/stock_inventory_discrepancy_security.xml',
        "security/ir.model.access.csv",
        "views/stock_cycle_count_view.xml",
        "views/stock_cycle_count_rule_view.xml",
        # "views/stock_warehouse_view.xml",
        # "views/stock_inventory_view.xml",
        # "views/stock_location_view.xml",
        # "views/stock_cycle_count_template.xml",
        "data/cycle_count_sequence.xml",
        # "data/cycle_count_ir_cron.xml",
        "reports/stock_location_accuracy_report.xml",
        "reports/stock_cycle_count_report.xml",
    ],
    "license": "OPL-1",
    "installable": True,
    "application": False,
    # 'pre_init_hook': 'pre_init',
}
