from . import crm_lead
from . import crm_stage
from . import crm_team
from . import customer_segment_analysis
from . import ir_module_module
from . import mail_compose_message
from . import mailing_mailing
from . import partner_segments
from . import res_company
from . import res_config_settings
from . import res_groups
from . import res_partner
from . import res_partner_rfm_segment_history
from . import rfm_partner_history
from . import rfm_partner_team_history
from . import rfm_segment_configuration
from . import rfm_segment_team_configuration
from . import sale_order
from . import setu_rfm_score
from . import setu_rfm_segment
from . import team_customer_segment