# -*- coding: utf-8 -*-

from . import res_partner
from . import compatible
from . import product_template
from . import payment_days
from . import res_partner_zone
from . import website
from . import origin_database
from . import temporary
from . import sale_order
from . import delivery_carrier
from . import stock_warehouse
from . import account_move
from . import approval_category
from . import approval_request
from . import product_product
from . import hr_employee_base
from . import purchase_order
from . import stock_move
from . import stock_picking
from . import shipping_incident
from . import stock_location
from . import follow_up_reminder
from . import mail_mail
from . import clasificaciones
from . import mail_activity
from . import res_config_setting
from . import subclases
