{
    'name': 'Customise Accounting Report',
    'version': '18.0.0.0',
    'license': 'LGPL-3',
    'category': 'Accounting/Accounting',
    'summary': """Customise Profit and Loss Report""",
    'website': 'https://www.setuconsulting.com',
    'support': 'support@setuconsulting.com',
    'description': """Customise Profit and Loss Report""",
    'author': 'Setu Consulting Services Pvt. Ltd',
    'sequence': 20,
    'depends': ['account', 'account_reports', 'point_of_sale', 'purchase', 'contacts','setu_invoice_cancellation','account_followup'],
    'data': [
        'data/debit_balance_cron.xml',
        'views/account_payment_term.xml',
        'views/account_move.xml',
        'views/res_config_settings.xml',
        'views/product_product_view.xml',
        'views/account_move_line.xml',
        'views/res_partner.xml',
        'views/account_report_view.xml',
        'views/account_report_add_field_marca.xml',
        'views/add_fiscal_folio_in_tree_view.xml',
        'views/custom_font_size_account_report.xml',
        'views/account_portal_templates.xml',
        'views/cfdi_40_header.xml',
        'views/invoice_report.xml',
        'views/l10n_mx_edi_report_bank_statement_line.xml',
        'data/customer_statement.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'setu_accounts_report_extended/static/src/components/**/*',
        ],
    },
    'installable': True,
    'auto_install': False,
}
