# -*- coding: utf-8 -*-
from . import legal_person
from . import sale
from . import picking
from . import price_list
from . import res_config_settings
from . import res_company
from . import res_partner
from . import sale_order_line
from . import stock_quant
from . import sale_report
from . import account_invoice
from . import sale_order_coupon_points
from . import product_template
from . import delivery_carrier
from . import stock_picking_type
from . import account_move_line
from . import stock_move
from . import stock_move_line
from . import product_product
