from . import res_config
from . import res_partner
from . import crm_case_categ
from . import crm_claim_stage
from . import crm_claim
from . import crm_team
from . import account_move
from . import stock_picking
from . import claim_state_history
from . import vendor_charge_status
from . import crm_action_type