from . import res_partner
from . import account_payment_term
from . import ir_actions_report
from . import account_move
from . import res_config_settings
from . import sale_order
from . import purchase_order
from . import product_product
from . import account_move_line
from . import account_report
from . import account_partner_ledger
from . import account_customer_statement
from . import account_followup
