from . import models
from . import ir_menus
from . import ir_model_access
from . import setu_access_rights
from . import setu_field_access
from . import setu_model_access
from . import setu_menu_access
from . import ir_ui_view
from . import setu_notebook_access
