from . import ram_memory_type
from . import ram_memory_capacity
from . import processor_speed
from . import processor_generation
from . import processor_model
from . import operative_system_version
from . import operative_system_type
from . import operative_system_distribution
from . import network_card_type
from . import network_card_mac_address
from . import hard_disk_capacity
from . import hard_disk_type
from . import account_asset
from . import hard_disk_line
from . import network_card_line
