from . import website
from . import preorder_sale_purchase_rel
from . import presale_purchase_rel
from . import stock_picking
from . import purchase_order_line
from . import purchase_order
from . import product_product
from . import product_template
from . import sale_order_line
from . import sale_order
from . import res_config_setting
from . import payment_transaction
from . import ir_http
from . import international_preorder_sale_purchase_rel
from . import account_move
from . import delivery_carrier
from . import stock_move
